apiVersion: v1

kind: Pod
metadata:
  name: devops-backend-pod
  labels:
    app: devops-backend
spec:
  containers:
    - name: devops-backend
      image: devops-backend:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 5000
    

