apiVersion: v1
kind: Service
metadata:
  name: devops-backend-service
spec:
  selector:
    app: devops-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
